### ISSUE TITLE
Errors from most recent release

### ISSUE THREAD

**Issue by matootie** [matootie/kiki#39]
```
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/app/kiki/plugins/levels/cogs.py", line 52, in allranks
    level = await utils.get_level(redis, member)
  File "/app/kiki/plugins/levels/utils/__init__.py", line 63, in get_level
    experience = await get_experience(redis, user)
  File "/app/kiki/plugins/levels/utils/__init__.py", line 25, in get_experience
    experience = await redis.get(f"xp:{user.id}")
AttributeError: 'NoneType' object has no attribute 'id'
```

```
Ignoring exception in on_member_update
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/app/kiki/plugins/levels/cogs.py", line 87, in on_member_update
    ae, ac = self.__eligible(state=after.voice)
  File "/app/kiki/plugins/levels/cogs.py", line 259, in __eligible
    raise AssertionError
AssertionError
```

**Comment by matootie** [comment]
Closed due to inactivity.
